language: go

sudo: false

branches:
  only:
    - master
    - develop

go:
  - 1.5.4
  - 1.6.3

script:
  - $HOME/gopath/bin/goveralls

install:
- make get
- make get_dev

script:
#- make check
- make test

after_script:
- make coverage
