language: go

sudo: false

branches:
  only:
    - master

go:
- 1.5.2

script:
  - $HOME/gopath/bin/goveralls

install:
- make get_deps
- make get_dev_deps

script:
- make check
- make test

after_script:
- make coverage